// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripMate.Infrastructure.Persistence;

#nullable disable

namespace TripMate.Infrastructure.Migrations
{
    [DbContext(typeof(TripMateDbContext))]
    [Migration("20260621194338_Trip")]
    partial class Trip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingItems");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("booked_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("booking_number");

                    b.Property<string>("BookingType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("booking_type");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int")
                        .HasColumnName("destination_id");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int")
                        .HasColumnName("number_of_people");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_price");

                    b.Property<DateOnly?>("TravelEndDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_end_date");

                    b.Property<DateOnly?>("TravelStartDate")
                        .HasColumnType("date")
                        .HasColumnName("travel_start_date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__5DE3A5B1F0325959");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "BookingNumber" }, "UQ__Bookings__3A30D2BC44476419")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.BookingTraveller", b =>
                {
                    b.Property<int>("TravelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("traveler_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TravelerId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nationality");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("passport_number");

                    b.HasKey("TravelerId")
                        .HasName("PK__BookingT__53C729FA564ADB6C");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingTravellers");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("destination_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("Activities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirportCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("airport_code");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("average_rating");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Itinerary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("longitude");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("main_image_url");

                    b.Property<decimal?>("MinPriceEstimate")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("min_price_estimate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("timezone");

                    b.Property<int?>("TripTypeId")
                        .HasColumnType("int")
                        .HasColumnName("trip_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DestinationId")
                        .HasName("PK__Destinat__55015391DD0D892B");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TripTypeId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.DestinationMedium", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int")
                        .HasColumnName("destination_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("media_url");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("MediaId")
                        .HasName("PK__Destinat__D0A840F466876063");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationMedia");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("favorite_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__46ACF4CBA1E9B777");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("airline_name");

                    b.Property<DateTime>("ArrivalDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("arrival_datetime");

                    b.Property<string>("BaggagePolicy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("baggage_policy");

                    b.Property<string>("CabinClass")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cabin_class");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DepartureDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure_datetime");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("destination_airport");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("flight_number");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OriginAirport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("origin_airport");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int?>("SeatsAvailable")
                        .HasColumnType("int")
                        .HasColumnName("seats_available");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("FlightId")
                        .HasName("PK__Flights__E3705765DA77E091");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842F9E802E30");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date")
                        .HasColumnName("available_from");

                    b.Property<DateOnly?>("AvailableTo")
                        .HasColumnType("date")
                        .HasColumnName("available_to");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("average_rating");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int")
                        .HasColumnName("destination_id");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExcludedText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("excluded_text");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<string>("IncludedText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("included_text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int")
                        .HasColumnName("max_guests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("short_description");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Tags")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tags");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PackageId")
                        .HasName("PK__Packages__63846AE84877CC47");

                    b.HasIndex("DestinationId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.PackageFlight", b =>
                {
                    b.Property<int>("PackageFlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("package_flight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageFlightId"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<string>("FlightRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("flight_role");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<decimal?>("PriceDifference")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_difference");

                    b.HasKey("PackageFlightId")
                        .HasName("PK__PackageF__51D92FC365C61F08");

                    b.HasIndex("FlightId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageFlights");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.PackageMedium", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("media_url");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("MediaId")
                        .HasName("PK__PackageM__D0A840F4725B70DD");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageMedia");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<string>("GatewayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gateway_type");

                    b.Property<DateTime>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_reference");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transaction_status");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__ED1FC9EA519FBE3F");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("location");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PostId")
                        .HasName("PK__Posts__3ED7876658D7ED95");

                    b.HasIndex("DestinationId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.PostMedium", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("media_url");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("MediaId")
                        .HasName("PK__PostMedi__D0A840F4F9DE00FE");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedia");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("item_type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.RecommendationLog", b =>
                {
                    b.Property<int>("RecLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecLogId"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("algorithm_version");

                    b.Property<bool>("Clicked")
                        .HasColumnType("bit")
                        .HasColumnName("clicked");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int")
                        .HasColumnName("destination_id");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 3)")
                        .HasColumnName("score");

                    b.Property<DateTime>("ShownAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("shown_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RecLogId")
                        .HasName("PK__Recommen__056DBA0666E7D7E4");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("RecommendationLogs");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("entity_type");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__60883D905D1AAAAD");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__760965CCFF80CC4C");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Traveller"
                        });
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.TripType", b =>
                {
                    b.Property<int>("TripTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trip_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("TripTypeId")
                        .HasName("PK__TripType__74B29FC1BF55D401");

                    b.ToTable("TripTypes");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("email_verified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit")
                        .HasColumnName("phone_verified");

                    b.Property<string>("PreferredCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("preferred_currency");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370FB16FDC5D");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164DB183792")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.UserAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("action_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<DateTime>("ActionTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("action_timestamp")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action_type");

                    b.Property<decimal?>("ActionValue")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("action_value");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int")
                        .HasColumnName("destination_id");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("flight_id");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ActionId")
                        .HasName("PK__UserActi__74EFC217D72B3519");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserActions");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.UserPreference", b =>
                {
                    b.Property<int>("UserPrefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_pref_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPrefId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("MaxBudget")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("max_budget");

                    b.Property<decimal?>("MinBudget")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("min_budget");

                    b.Property<string>("PreferredAirlines")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("preferred_airlines");

                    b.Property<string>("PreferredSeason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("preferred_season");

                    b.Property<int?>("PreferredTripTypeId")
                        .HasColumnType("int")
                        .HasColumnName("preferred_trip_type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserPrefId")
                        .HasName("PK__UserPref__BDC9BDBE1BE3CCF6");

                    b.HasIndex("PreferredTripTypeId");

                    b.HasIndex(new[] { "UserId" }, "UQ_UserPreferences_User")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("UserInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserInteractions");
                });

            modelBuilder.Entity("BookingItem", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Booking", "Booking")
                        .WithMany("Items")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Booking", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Destination", "Destination")
                        .WithMany("Bookings")
                        .HasForeignKey("DestinationId")
                        .HasConstraintName("FK_Bookings_Destinations");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_Bookings_Flights");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Package", "Package")
                        .WithMany("Bookings")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_Bookings_Packages");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Users");

                    b.Navigation("Destination");

                    b.Navigation("Flight");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.BookingTraveller", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Booking", "Booking")
                        .WithMany("BookingTravellers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingTravellers_Bookings");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Destination", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.TripType", "TripType")
                        .WithMany("Destinations")
                        .HasForeignKey("TripTypeId")
                        .HasConstraintName("FK_Destinations_TripTypes");

                    b.Navigation("Category");

                    b.Navigation("TripType");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.DestinationMedium", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Destination", "Destination")
                        .WithMany("DestinationMedia")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DestinationMedia_Destinations");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Favorite", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Notification", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Package", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Destination", "Destination")
                        .WithMany("Packages")
                        .HasForeignKey("DestinationId")
                        .IsRequired()
                        .HasConstraintName("FK_Packages_Destinations");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.PackageFlight", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Flight", "Flight")
                        .WithMany("PackageFlights")
                        .HasForeignKey("FlightId")
                        .IsRequired()
                        .HasConstraintName("FK_PackageFlights_Flights");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Package", "Package")
                        .WithMany("PackageFlights")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PackageFlights_Packages");

                    b.Navigation("Flight");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.PackageMedium", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Package", "Package")
                        .WithMany("PackageMedia")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PackageMedia_Packages");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Payment", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Bookings");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Post", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Destination", "Destination")
                        .WithMany("Posts")
                        .HasForeignKey("DestinationId");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Package", null)
                        .WithMany("Posts")
                        .HasForeignKey("PackageId");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Users");

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.PostMedium", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Post", "Post")
                        .WithMany("PostMedia")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Rating", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.RecommendationLog", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Destination", "Destination")
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_RecommendationLogs_Destinations");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Flight", "Flight")
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_RecommendationLogs_Flights");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Package", "Package")
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_RecommendationLogs_Packages");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("RecommendationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecommendationLogs_Users");

                    b.Navigation("Destination");

                    b.Navigation("Flight");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Review", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.UserAction", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Destination", "Destination")
                        .WithMany("UserActions")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_UserActions_Destinations");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Flight", "Flight")
                        .WithMany("UserActions")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK_UserActions_Flights");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.Package", "Package")
                        .WithMany("UserActions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_UserActions_Packages");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("UserActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserActions_Users");

                    b.Navigation("Destination");

                    b.Navigation("Flight");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.UserPreference", b =>
                {
                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.TripType", "PreferredTripType")
                        .WithMany("UserPreferences")
                        .HasForeignKey("PreferredTripTypeId")
                        .HasConstraintName("FK_UserPreferences_TripTypes");

                    b.HasOne("TripMate.Infrastructure.Persistence.Entities.User", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("TripMate.Infrastructure.Persistence.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPreferences_Users");

                    b.Navigation("PreferredTripType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Booking", b =>
                {
                    b.Navigation("BookingTravellers");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Destination", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("DestinationMedia");

                    b.Navigation("Packages");

                    b.Navigation("Posts");

                    b.Navigation("RecommendationLogs");

                    b.Navigation("UserActions");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PackageFlights");

                    b.Navigation("RecommendationLogs");

                    b.Navigation("UserActions");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Package", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PackageFlights");

                    b.Navigation("PackageMedia");

                    b.Navigation("Posts");

                    b.Navigation("RecommendationLogs");

                    b.Navigation("UserActions");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Post", b =>
                {
                    b.Navigation("PostMedia");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.TripType", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("TripMate.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Ratings");

                    b.Navigation("RecommendationLogs");

                    b.Navigation("Reviews");

                    b.Navigation("UserActions");

                    b.Navigation("UserPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
